import java.util.Properties

plugins {
    // The Kotlin plugin is already on the build classpath through buildSrc
    id("org.jetbrains.kotlin.jvm")
}

/*
 * Shares the platform-neutral half of the Android app with the desktop client:
 * protocol beans, subscription importers/parsers and a few ktx helpers.
 *
 * Everything that is bound to Android (Context, Parcelable, Room, ViewBinding,
 * R, the VPN service) is excluded and replaced by a desktop shim under
 * `src/main/kotlin/desktopshim` with the very same package names, so both the
 * Android app and the desktop client keep compiling from one source of truth.
 *
 * NOTE: the shims are written in Kotlin on purpose. Kotlin cannot resolve Java
 * sources that live in a second source directory of a mixed module, and the
 * desktop shims have to be visible to the Kotlin compiler because the shared
 * Java beans inherit from them.
 */
val appSrc = rootProject.file("app/src/main/java")

val sharedIncludes = listOf(
    "io/nekohasekai/sagernet/fmt/**",
    "io/nekohasekai/sagernet/group/**",
    "io/nekohasekai/sagernet/ktx/**",
    "io/nekohasekai/sagernet/Constants.kt",
    "io/nekohasekai/sagernet/utils/Commandline.kt",
    "io/nekohasekai/sagernet/BuildConfig.kt",
    "com/github/shadowsocks/plugin/PluginOptions.kt",
    "desktopshim/**",
)

val sharedExcludes = listOf(
    "io/nekohasekai/sagernet/fmt/PluginEntry.kt",
    "io/nekohasekai/sagernet/fmt/Serializable.kt",
    "io/nekohasekai/sagernet/fmt/KryoConverters.java",
    "io/nekohasekai/sagernet/fmt/TypeMap.kt",
    "io/nekohasekai/sagernet/fmt/UniversalFmt.kt",
    // subscription updaters: Android HTTP stack, WorkManager, notifications
    "io/nekohasekai/sagernet/group/AppUpdater.kt",
    "io/nekohasekai/sagernet/group/AgeUpdater.kt",
    "io/nekohasekai/sagernet/group/RawUpdater.kt",
    "io/nekohasekai/sagernet/group/SIP008Updater.kt",
    "io/nekohasekai/sagernet/group/GroupUpdater.kt",
    "io/nekohasekai/sagernet/group/GroupInterfaceAdapter.kt",
    // Android-only ktx helpers
    "io/nekohasekai/sagernet/ktx/Context.kt",
    "io/nekohasekai/sagernet/ktx/Dialogs.kt",
    "io/nekohasekai/sagernet/ktx/Dimens.kt",
    "io/nekohasekai/sagernet/ktx/Formats.kt",
    "io/nekohasekai/sagernet/ktx/Hwid.kt",
    "io/nekohasekai/sagernet/ktx/Kryos.kt",
    "io/nekohasekai/sagernet/ktx/Layouts.kt",
    "io/nekohasekai/sagernet/ktx/Logs.kt",
    "io/nekohasekai/sagernet/ktx/Preferences.kt",
    "io/nekohasekai/sagernet/ktx/Utils.kt",
    // Android plugin registry
    "com/github/shadowsocks/plugin/PluginConfiguration.kt",
    // Clash rule parser produces Room entities (`RuleEntity`)
    "io/nekohasekai/sagernet/group/ClashRoutingParser.kt",
)

/** `BuildConfig` is generated from `version.properties` so it cannot drift. */
val versionProperties = Properties().apply {
    rootProject.file("version.properties").inputStream().use { load(it) }
}
val generatedBuildConfigDir = layout.buildDirectory.dir("generated/desktopBuildConfig")

val generateDesktopBuildConfig = tasks.register("generateDesktopBuildConfig") {
    val outputDir = generatedBuildConfigDir
    val versionName = versionProperties.getProperty("VERSION_NAME").trim()
    val versionCode = versionProperties.getProperty("VERSION_CODE").trim()
    val packageName = versionProperties.getProperty("PACKAGE_NAME").trim()
    inputs.property("versionName", versionName)
    inputs.property("versionCode", versionCode)
    outputs.dir(outputDir)
    doLast {
        val target = outputDir.get().asFile.resolve("io/nekohasekai/sagernet")
        target.mkdirs()
        target.resolve("BuildConfig.kt").writeText(
            """
            |// Generated by :desktop:shared:generateDesktopBuildConfig. Do not edit.
            |package io.nekohasekai.sagernet
            |
            |object BuildConfig {
            |
            |    const val DEBUG = false
            |    const val APPLICATION_ID = "$packageName.desktop"
            |    const val VERSION_NAME = "$versionName"
            |    const val VERSION_CODE = $versionCode
            |
            |}
            |
            """.trimMargin()
        )
    }
}

kotlin {
    jvmToolchain(21)
}

sourceSets["main"].apply {
    java.setSrcDirs(listOf("src/main/java", appSrc))
    java.setIncludes(listOf("io/nekohasekai/sagernet/fmt/**", "io/nekohasekai/sagernet/group/**", "androidx/**"))
    java.exclude(sharedExcludes)
    kotlin.setSrcDirs(listOf("src/main/kotlin", appSrc, generateDesktopBuildConfig))
    kotlin.setIncludes(sharedIncludes)
    kotlin.exclude(sharedExcludes)
}

dependencies {
    api(libs.gson)
    implementation(libs.snakeyaml)
    implementation(libs.kryo)
    implementation(libs.jini.lib)
    implementation(libs.kotlinx.coroutines.core)
}
